# Generated by Django 3.0.7 on 2020-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_excelsavermodelmonthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('budget', models.FloatField(max_length=50, null=True)),
                ('allocation', models.FloatField(max_length=50, null=True)),
                ('total_allocation', models.FloatField(max_length=50, null=True)),
                ('balance', models.FloatField(max_length=50, null=True)),
                ('month', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
