# Generated by Django 3.0.5 on 2020-07-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0004_economicexpenditure1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicexpenditure',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='economicexpenditure1',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mdabudget',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
