# Generated by Django 2.2.13 on 2020-06-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroservicesApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100, null=True)),
                ('budget', models.FloatField(max_length=50, null=True)),
                ('allocation', models.FloatField(max_length=50, null=True)),
                ('total_allocation', models.FloatField(max_length=50, null=True)),
                ('balance', models.FloatField(max_length=50, null=True)),
                ('month', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('budget', models.FloatField(max_length=50, null=True)),
                ('allocation', models.FloatField(max_length=50, null=True)),
                ('total_allocation', models.FloatField(max_length=50, null=True)),
                ('balance', models.FloatField(max_length=50, null=True)),
                ('month', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('revenue', models.FloatField(max_length=50, null=True)),
                ('total_revenue', models.FloatField(max_length=50, null=True)),
                ('month', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('budget', models.FloatField(max_length=50, null=True)),
                ('expenses', models.FloatField(max_length=50, null=True)),
                ('total_expenses', models.FloatField(max_length=50, null=True)),
                ('balance', models.FloatField(max_length=50, null=True)),
                ('month', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MDABudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mda', models.CharField(max_length=100, null=True)),
                ('budget', models.FloatField(max_length=50, null=True)),
                ('allocation', models.FloatField(max_length=50, null=True)),
                ('total_allocation', models.FloatField(max_length=50, null=True)),
                ('balance', models.FloatField(max_length=50, null=True)),
                ('month', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book_item',
        ),
        migrations.DeleteModel(
            name='Computer_asset',
        ),
        migrations.DeleteModel(
            name='House_asset',
        ),
    ]
