# Generated by Django 2.2.13 on 2020-06-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroservicesApi', '0002_auto_20200630_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDA_name', models.CharField(max_length=100)),
                ('project_recipient_name', models.CharField(max_length=120)),
                ('project_name', models.TextField()),
                ('project_amount', models.FloatField()),
                ('project_date', models.DateField()),
            ],
        ),
    ]
